language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      # kubuntu-backports contains newer versions of cmake to install
      - kubuntu-backports
    packages:
      - cmake
      - ocl-icd-opencl-dev

env:
  global:
    - CLTUNE_ROOT=${TRAVIS_BUILD_DIR}/bin/cltune

before_install:
  - cmake --version;
  - ${CC} --version;
  - ${CXX} --version;

before_script:
  - mkdir -p ${CLTUNE_ROOT}
  - pushd ${CLTUNE_ROOT}
  - cmake -DSAMPLES=ON -DTESTS=ON ${TRAVIS_BUILD_DIR}

script:
  - make

branches:
  only:
    - master
    - development

notifications:
  email: false
